<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id()->increments(true);
            $table->string('name')->unique();
            $table->string('code')->unique();
            $table->string('iso2')->unique();
            $table->string('iso3')->unique();
            $table->string('phone_code')->nullable();
            $table->string('currency')->nullable();
            $table->string('currency_code')->nullable();
            $table->string('currency_symbol')->nullable();
            $table->string('flag')->nullable();
            $table->boolean('isActive')->default(0);
            $table->timestamps();
        });

        //Insert these countries
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'iso2' => 'AF', 'iso3' => 'AFG', 'phone_code' => '+93', 'currency' => 'AFN', 'currency_code' => 'AFN', 'currency_symbol' => '؋', 'flag' => '🇦🇫', 'isActive' => 0],
            ['name' => 'Albania', 'code' => 'AL', 'iso2' => 'AL', 'iso3' => 'ALB', 'phone_code' => '+355', 'currency' => 'ALL', 'currency_code' => 'ALL', 'currency_symbol' => 'Lek', 'flag' => '🇦🇱', 'isActive' => 0],
            ['name' => 'Algeria', 'code' => 'DZ', 'iso2' => 'DZ', 'iso3' => 'DZA', 'phone_code' => '+213', 'currency' => 'DZD', 'currency_code' => 'DZD', 'currency_symbol' => 'دج', 'flag' => '🇩🇿', 'isActive' => 0],
            ['name' => 'American Samoa', 'code' => 'AS', 'iso2' => 'AS', 'iso3' => 'ASM', 'phone_code' => '+1-684', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '$', 'flag' => '🇦🇸', 'isActive' => 0],
            ['name' => 'Andorra', 'code' => 'AD', 'iso2' => 'AD', 'iso3' => 'AND', 'phone_code' => '+376', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇦🇩', 'isActive' => 0],
            ['name' => 'Angola', 'code' => 'AO', 'iso2' => 'AO', 'iso3' => 'AGO', 'phone_code' => '+244', 'currency' => 'AOA', 'currency_code' => 'AOA', 'currency_symbol' => 'Kz', 'flag' => '🇦🇴', 'isActive' => 0],
            ['name' => 'Anguilla', 'code' => 'AI', 'iso2' => 'AI', 'iso3' => 'AIA', 'phone_code' => '+1-264', 'currency' => 'XCD', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'flag' => '🇦🇮', 'isActive' => 0],
            ['name' => 'Antarctica', 'code' => 'AQ', 'iso2' => 'AQ', 'iso3' => 'ATA', 'phone_code' => '+672', 'currency' => '', 'currency_code' => '', 'currency_symbol' => '', 'flag' => '🇦🇶', 'isActive' => 0],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'iso2' => 'AG', 'iso3' => 'ATG', 'phone_code' => '+1-268', 'currency' => 'XCD', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'flag' => '🇦🇬', 'isActive' => 0],
            ['name' => 'Argentina', 'code' => 'AR', 'iso2' => 'AR', 'iso3' => 'ARG', 'phone_code' => '+54', 'currency' => 'ARS', 'currency_code' => 'ARS', 'currency_symbol' => '$', 'flag' => '🇦🇷', 'isActive' => 0],
            ['name' => 'Armenia', 'code' => 'AM', 'iso2' => 'AM', 'iso3' => 'ARM', 'phone_code' => '+374', 'currency' => 'AMD', 'currency_code' => 'AMD', 'currency_symbol' => '֏', 'flag' => '🇦🇲', 'isActive' => 0],
            ['name' => 'Aruba', 'code' => 'AW', 'iso2' => 'AW', 'iso3' => 'ABW', 'phone_code' => '+297', 'currency' => 'AWG', 'currency_code' => 'AWG', 'currency_symbol' => 'ƒ', 'flag' => '🇦🇼', 'isActive' => 0],
            ['name' => 'Australia', 'code' => 'AU', 'iso2' => 'AU', 'iso3' => 'AUS', 'phone_code' => '+61', 'currency' => 'AUD', 'currency_code' => 'AUD', 'currency_symbol' => '$', 'flag' => '🇦🇺', 'isActive' => 0],
            ['name' => 'Austria', 'code' => 'AT', 'iso2' => 'AT', 'iso3' => 'AUT', 'phone_code' => '+43', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇦🇹', 'isActive' => 0],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'iso2' => 'AZ', 'iso3' => 'AZE', 'phone_code' => '+994', 'currency' => 'AZN', 'currency_code' => 'AZN', 'currency_symbol' => '₼', 'flag' => '🇦🇿', 'isActive' => 0],
            ['name' => 'Bahamas', 'code' => 'BS', 'iso2' => 'BS', 'iso3' => 'BHS', 'phone_code' => '+1-242', 'currency' => 'BSD', 'currency_code' => 'BSD', 'currency_symbol' => '$', 'flag' => '🇧🇸', 'isActive' => 0],
            ['name' => 'Bahrain', 'code' => 'BH', 'iso2' => 'BH', 'iso3' => 'BHR', 'phone_code' => '+973', 'currency' => 'BHD', 'currency_code' => 'BHD', 'currency_symbol' => '.د.ب', 'flag' => '🇧🇭', 'isActive' => 0],
            ['name' => 'Bangladesh', 'code' => 'BD', 'iso2' => 'BD', 'iso3' => 'BGD', 'phone_code' => '+880', 'currency' => 'BDT', 'currency_code' => 'BDT', 'currency_symbol' => '৳', 'flag' => '🇧🇩', 'isActive' => 0],
            ['name' => 'Barbados', 'code' => 'BB', 'iso2' => 'BB', 'iso3' => 'BRB', 'phone_code' => '+1-246', 'currency' => 'BBD', 'currency_code' => 'BBD', 'currency_symbol' => '$', 'flag' => '🇧🇧', 'isActive' => 0],
            ['name' => 'Belarus', 'code' => 'BY', 'iso2' => 'BY', 'iso3' => 'BLR', 'phone_code' => '+375', 'currency' => 'BYN', 'currency_code' => 'BYN', 'currency_symbol' => 'Br', 'flag' => '🇧🇾', 'isActive' => 0],
            ['name' => 'Belgium', 'code' => 'BE', 'iso2' => 'BE', 'iso3' => 'BEL', 'phone_code' => '+32', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇧🇪', 'isActive' => 0],
            ['name' => 'Belize', 'code' => 'BZ', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'phone_code' => '+501', 'currency' => 'BZD', 'currency_code' => 'BZD', 'currency_symbol' => '$', 'flag' => '🇧🇿', 'isActive' => 0],
            ['name' => 'Benin', 'code' => 'BJ', 'iso2' => 'BJ', 'iso3' => 'BEN', 'phone_code' => '+229', 'currency' => 'XOF', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'flag' => '🇧🇯', 'isActive' => 0],
            ['name' => 'Bermuda', 'code' => 'BM', 'iso2' => 'BM', 'iso3' => 'BMU', 'phone_code' => '+1-441', 'currency' => 'BMD', 'currency_code' => 'BMD', 'currency_symbol' => '$', 'flag' => '🇧🇲', 'isActive' => 0],
            ['name' => 'Bhutan', 'code' => 'BT', 'iso2' => 'BT', 'iso3' => 'BTN', 'phone_code' => '+975', 'currency' => 'BTN', 'currency_code' => 'BTN', 'currency_symbol' => 'Nu.', 'flag' => '🇧🇹', 'isActive' => 0],
            ['name' => 'Bolivia', 'code' => 'BO', 'iso2' => 'BO', 'iso3' => 'BOL', 'phone_code' => '+591', 'currency' => 'BOB', 'currency_code' => 'BOB', 'currency_symbol' => 'Bs.', 'flag' => '🇧🇴', 'isActive' => 0],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'iso2' => 'BA', 'iso3' => 'BIH', 'phone_code' => '+387', 'currency' => 'BAM', 'currency_code' => 'BAM', 'currency_symbol' => 'KM', 'flag' => '🇧🇦', 'isActive' => 0],
            ['name' => 'Botswana', 'code' => 'BW', 'iso2' => 'BW', 'iso3' => 'BWA', 'phone_code' => '+267', 'currency' => 'BWP', 'currency_code' => 'BWP', 'currency_symbol' => 'P', 'flag' => '🇧🇼', 'isActive' => 0],
            ['name' => 'Brazil', 'code' => 'BR', 'iso2' => 'BR', 'iso3' => 'BRA', 'phone_code' => '+55', 'currency' => 'BRL', 'currency_code' => 'BRL', 'currency_symbol' => 'R$', 'flag' => '🇧🇷', 'isActive' => 0],
            ['name' => 'Brunei', 'code' => 'BN', 'iso2' => 'BN', 'iso3' => 'BRN', 'phone_code' => '+673', 'currency' => 'BND', 'currency_code' => 'BND', 'currency_symbol' => '$', 'flag' => '🇧🇳', 'isActive' => 0],
            ['name' => 'Bulgaria', 'code' => 'BG', 'iso2' => 'BG', 'iso3' => 'BGR', 'phone_code' => '+359', 'currency' => 'BGN', 'currency_code' => 'BGN', 'currency_symbol' => 'лв', 'flag' => '🇧🇬', 'isActive' => 0],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'iso2' => 'BF', 'iso3' => 'BFA', 'phone_code' => '+226', 'currency' => 'XOF', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'flag' => '🇧🇫', 'isActive' => 0],
            ['name' => 'Burundi', 'code' => 'BI', 'iso2' => 'BI', 'iso3' => 'BDI', 'phone_code' => '+257', 'currency' => 'BIF', 'currency_code' => 'BIF', 'currency_symbol' => 'FBu', 'flag' => '🇧🇮', 'isActive' => 0],
            ['name' => 'Cabo Verde', 'code' => 'CV', 'iso2' => 'CV', 'iso3' => 'CPV', 'phone_code' => '+238', 'currency' => 'CVE', 'currency_code' => 'CVE', 'currency_symbol' => 'Esc', 'flag' => '🇨🇻', 'isActive' => 0],
            ['name' => 'Cambodia', 'code' => 'KH', 'iso2' => 'KH', 'iso3' => 'KHM', 'phone_code' => '+855', 'currency' => 'KHR', 'currency_code' => 'KHR', 'currency_symbol' => '៛', 'flag' => '🇰🇭', 'isActive' => 0],
            ['name' => 'Cameroon', 'code' => 'CM', 'iso2' => 'CM', 'iso3' => 'CMR', 'phone_code' => '+237', 'currency' => 'XAF', 'currency_code' => 'XAF', 'currency_symbol' => 'CFA', 'flag' => '🇨🇲', 'isActive' => 0],
            ['name' => 'Canada', 'code' => 'CA', 'iso2' => 'CA', 'iso3' => 'CAN', 'phone_code' => '+1', 'currency' => 'CAD', 'currency_code' => 'CAD', 'currency_symbol' => '$', 'flag' => '🇨🇦', 'isActive' => 1],
            ['name' => 'Central African Republic', 'code' => 'CF', 'iso2' => 'CF', 'iso3' => 'CAF', 'phone_code' => '+236', 'currency' => 'XAF', 'currency_code' => 'XAF', 'currency_symbol' => 'CFA', 'flag' => '🇨🇫', 'isActive' => 0],
            ['name' => 'Chad', 'code' => 'TD', 'iso2' => 'TD', 'iso3' => 'TCD', 'phone_code' => '+235', 'currency' => 'XAF', 'currency_code' => 'XAF', 'currency_symbol' => 'CFA', 'flag' => '🇹🇩', 'isActive' => 0],
            ['name' => 'Chile', 'code' => 'CL', 'iso2' => 'CL', 'iso3' => 'CHL', 'phone_code' => '+56', 'currency' => 'CLP', 'currency_code' => 'CLP', 'currency_symbol' => '', 'flag' => '🇨🇱', 'isActive' => 0],
            ['name' => 'China', 'code' => 'CN', 'iso2' => 'CN', 'iso3' => 'CHN', 'phone_code' => '+86', 'currency' => 'CNY', 'currency_code' => 'CNY', 'currency_symbol' => '¥', 'flag' => '🇨🇳', 'isActive' => 0],
            ['name' => 'Colombia', 'code' => 'CO', 'iso2' => 'CO', 'iso3' => 'COL', 'phone_code' => '+57', 'currency' => 'COP', 'currency_code' => 'COP', 'currency_symbol' => '', 'flag' => '🇨🇴', 'isActive' => 0],
            ['name' => 'Comoros', 'code' => 'KM', 'iso2' => 'KM', 'iso3' => 'COM', 'phone_code' => '+269', 'currency' => 'KMF', 'currency_code' => 'KMF', 'currency_symbol' => 'CF', 'flag' => '🇰🇲', 'isActive' => 0],
            ['name' => 'Congo', 'code' => 'CG', 'iso2' => 'CG', 'iso3' => 'COG', 'phone_code' => '+242', 'currency' => 'XAF', 'currency_code' => 'XAF', 'currency_symbol' => 'CFA', 'flag' => '🇨🇬', 'isActive' => 0],
            ['name' => 'Congo, The Democratic Republic of the', 'code' => 'CD', 'iso2' => 'CD', 'iso3' => 'COD', 'phone_code' => '+243', 'currency' => 'CDF', 'currency_code' => 'CDF', 'currency_symbol' => 'FC', 'flag' => '🇨🇩', 'isActive' => 0],
            ['name' => 'Cook Islands', 'code' => 'CK', 'iso2' => 'CK', 'iso3' => 'COK', 'phone_code' => '+682', 'currency' => 'NZD', 'currency_code' => 'NZD', 'currency_symbol' => '', 'flag' => '🇨🇰', 'isActive' => 0],
            ['name' => 'Costa Rica', 'code' => 'CR', 'iso2' => 'CR', 'iso3' => 'CRI', 'phone_code' => '+506', 'currency' => 'CRC', 'currency_code' => 'CRC', 'currency_symbol' => '₡', 'flag' => '🇨🇷', 'isActive' => 0],
            ['name' => 'Croatia', 'code' => 'HR', 'iso2' => 'HR', 'iso3' => 'HRV', 'phone_code' => '+385', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇭🇷', 'isActive' => 0],
            ['name' => 'Cuba', 'code' => 'CU', 'iso2' => 'CU', 'iso3' => 'CUB', 'phone_code' => '+53', 'currency' => 'CUP', 'currency_code' => 'CUP', 'currency_symbol' => '', 'flag' => '🇨🇺', 'isActive' => 0],
            ['name' => 'Curaçao', 'code' => 'CW', 'iso2' => 'CW', 'iso3' => 'CUW', 'phone_code' => '+599', 'currency' => 'ANG', 'currency_code' => 'ANG', 'currency_symbol' => 'ƒ', 'flag' => '🇨🇼', 'isActive' => 0],
            ['name' => 'Cyprus', 'code' => 'CY', 'iso2' => 'CY', 'iso3' => 'CYP', 'phone_code' => '+357', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇨🇾', 'isActive' => 0],
            ['name' => 'Czechia', 'code' => 'CZ', 'iso2' => 'CZ', 'iso3' => 'CZE', 'phone_code' => '+420', 'currency' => 'CZK', 'currency_code' => 'CZK', 'currency_symbol' => 'Kč', 'flag' => '🇨🇿', 'isActive' => 0],
            ['name' => 'Denmark', 'code' => 'DK', 'iso2' => 'DK', 'iso3' => 'DNK', 'phone_code' => '+45', 'currency' => 'DKK', 'currency_code' => 'DKK', 'currency_symbol' => 'kr', 'flag' => '🇩🇰', 'isActive' => 0],
            ['name' => 'Djibouti', 'code' => 'DJ', 'iso2' => 'DJ', 'iso3' => 'DJI', 'phone_code' => '+253', 'currency' => 'DJF', 'currency_code' => 'DJF', 'currency_symbol' => 'Fdj', 'flag' => '🇩🇯', 'isActive' => 0],
            ['name' => 'Dominica', 'code' => 'DM', 'iso2' => 'DM', 'iso3' => 'DMA', 'phone_code' => '+1-767', 'currency' => 'XCD', 'currency_code' => 'XCD', 'currency_symbol' => '', 'flag' => '🇩🇲', 'isActive' => 0],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'iso2' => 'DO', 'iso3' => 'DOM', 'phone_code' => '+1-809, 1-829, 1-849', 'currency' => 'DOP', 'currency_code' => 'DOP', 'currency_symbol' => '', 'flag' => '🇩🇴', 'isActive' => 0],
            ['name' => 'Ecuador', 'code' => 'EC', 'iso2' => 'EC', 'iso3' => 'ECU', 'phone_code' => '+593', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇪🇨', 'isActive' => 0],
            ['name' => 'Egypt', 'code' => 'EG', 'iso2' => 'EG', 'iso3' => 'EGY', 'phone_code' => '+20', 'currency' => 'EGP', 'currency_code' => 'EGP', 'currency_symbol' => '£', 'flag' => '🇪🇬', 'isActive' => 0],
            ['name' => 'El Salvador', 'code' => 'SV', 'iso2' => 'SV', 'iso3' => 'SLV', 'phone_code' => '+503', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇸🇻', 'isActive' => 0],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'phone_code' => '+240', 'currency' => 'XAF', 'currency_code' => 'XAF', 'currency_symbol' => 'CFA', 'flag' => '🇬🇶', 'isActive' => 0],
            ['name' => 'Eritrea', 'code' => 'ER', 'iso2' => 'ER', 'iso3' => 'ERI', 'phone_code' => '+291', 'currency' => 'ERN', 'currency_code' => 'ERN', 'currency_symbol' => 'Nfk', 'flag' => '🇪🇷', 'isActive' => 0],
            ['name' => 'Estonia', 'code' => 'EE', 'iso2' => 'EE', 'iso3' => 'EST', 'phone_code' => '+372', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇪🇪', 'isActive' => 0],
            ['name' => 'Eswatini', 'code' => 'SZ', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'phone_code' => '+268', 'currency' => 'SZL', 'currency_code' => 'SZL', 'currency_symbol' => 'L', 'flag' => '🇸🇿', 'isActive' => 0],
            ['name' => 'Ethiopia', 'code' => 'ET', 'iso2' => 'ET', 'iso3' => 'ETH', 'phone_code' => '+251', 'currency' => 'ETB', 'currency_code' => 'ETB', 'currency_symbol' => 'Br', 'flag' => '🇪🇹', 'isActive' => 0],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'iso2' => 'FK', 'iso3' => 'FLK', 'phone_code' => '+500', 'currency' => 'FKP', 'currency_code' => 'FKP', 'currency_symbol' => '£', 'flag' => '🇫🇰', 'isActive' => 0],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'iso2' => 'FO', 'iso3' => 'FRO', 'phone_code' => '+298', 'currency' => 'DKK', 'currency_code' => 'DKK', 'currency_symbol' => 'kr', 'flag' => '🇫🇴', 'isActive' => 0],
            ['name' => 'Fiji', 'code' => 'FJ', 'iso2' => 'FJ', 'iso3' => 'FJI', 'phone_code' => '+679', 'currency' => 'FJD', 'currency_code' => 'FJD', 'currency_symbol' => '', 'flag' => '🇫🇯', 'isActive' => 0],
            ['name' => 'Finland', 'code' => 'FI', 'iso2' => 'FI', 'iso3' => 'FIN', 'phone_code' => '+358', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇫🇮', 'isActive' => 0],
            ['name' => 'France', 'code' => 'FR', 'iso2' => 'FR', 'iso3' => 'FRA', 'phone_code' => '+33', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇫🇷', 'isActive' => 0],
            ['name' => 'French Guiana', 'code' => 'GF', 'iso2' => 'GF', 'iso3' => 'GUF', 'phone_code' => '+594', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇬🇫', 'isActive' => 0],
            ['name' => 'French Polynesia', 'code' => 'PF', 'iso2' => 'PF', 'iso3' => 'PYF', 'phone_code' => '+689', 'currency' => 'XPF', 'currency_code' => 'XPF', 'currency_symbol' => 'CFPF', 'flag' => '🇵🇫', 'isActive' => 0],
            ['name' => 'Gabon', 'code' => 'GA', 'iso2' => 'GA', 'iso3' => 'GAB', 'phone_code' => '+241', 'currency' => 'XAF', 'currency_code' => 'XAF', 'currency_symbol' => 'CFA', 'flag' => '🇬🇦', 'isActive' => 0],
            ['name' => 'Gambia', 'code' => 'GM', 'iso2' => 'GM', 'iso3' => 'GMB', 'phone_code' => '+220', 'currency' => 'GMD', 'currency_code' => 'GMD', 'currency_symbol' => 'D', 'flag' => '🇬🇲', 'isActive' => 0],
            ['name' => 'Georgia', 'code' => 'GE', 'iso2' => 'GE', 'iso3' => 'GEO', 'phone_code' => '+995', 'currency' => 'GEL', 'currency_code' => 'GEL', 'currency_symbol' => '₾', 'flag' => '🇬🇪', 'isActive' => 0],
            ['name' => 'Germany', 'code' => 'DE', 'iso2' => 'DE', 'iso3' => 'DEU', 'phone_code' => '+49', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇩🇪', 'isActive' => 0],
            ['name' => 'Ghana', 'code' => 'GH', 'iso2' => 'GH', 'iso3' => 'GHA', 'phone_code' => '+233', 'currency' => 'GHS', 'currency_code' => 'GHS', 'currency_symbol' => 'GH₵', 'flag' => '🇬🇭', 'isActive' => 0],
            ['name' => 'Gibraltar', 'code' => 'GI', 'iso2' => 'GI', 'iso3' => 'GIB', 'phone_code' => '+350', 'currency' => 'GIP', 'currency_code' => 'GIP', 'currency_symbol' => '£', 'flag' => '🇬🇮', 'isActive' => 0],
            ['name' => 'Greece', 'code' => 'GR', 'iso2' => 'GR', 'iso3' => 'GRC', 'phone_code' => '+30', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇬🇷', 'isActive' => 0],
            ['name' => 'Greenland', 'code' => 'GL', 'iso2' => 'GL', 'iso3' => 'GRL', 'phone_code' => '+299', 'currency' => 'DKK', 'currency_code' => 'DKK', 'currency_symbol' => 'kr', 'flag' => '🇬🇱', 'isActive' => 0],
            ['name' => 'Grenada', 'code' => 'GD', 'iso2' => 'GD', 'iso3' => 'GRD', 'phone_code' => '+1-473', 'currency' => 'XCD', 'currency_code' => 'XCD', 'currency_symbol' => '', 'flag' => '🇬🇩', 'isActive' => 0],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'iso2' => 'GP', 'iso3' => 'GLP', 'phone_code' => '+590', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇬🇵', 'isActive' => 0],
            ['name' => 'Guam', 'code' => 'GU', 'iso2' => 'GU', 'iso3' => 'GUM', 'phone_code' => '+1-671', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '$', 'flag' => '🇬🇺', 'isActive' => 0],
            ['name' => 'Guatemala', 'code' => 'GT', 'iso2' => 'GT', 'iso3' => 'GTM', 'phone_code' => '+502', 'currency' => 'GTQ', 'currency_code' => 'GTQ', 'currency_symbol' => 'Q', 'flag' => '🇬🇹', 'isActive' => 0],
            ['name' => 'Guernsey', 'code' => 'GG', 'iso2' => 'GG', 'iso3' => 'GGY', 'phone_code' => '+44-1481', 'currency' => 'GBP', 'currency_code' => 'GBP', 'currency_symbol' => '£', 'flag' => '🇬🇬', 'isActive' => 0],
            ['name' => 'Guinea', 'code' => 'GN', 'iso2' => 'GN', 'iso3' => 'GIN', 'phone_code' => '+224', 'currency' => 'GNF', 'currency_code' => 'GNF', 'currency_symbol' => 'FG', 'flag' => '🇬🇳', 'isActive' => 0],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'iso2' => 'GW', 'iso3' => 'GNB', 'phone_code' => '+245', 'currency' => 'XOF', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'flag' => '🇬🇼', 'isActive' => 0],
            ['name' => 'Guyana', 'code' => 'GY', 'iso2' => 'GY', 'iso3' => 'GUY', 'phone_code' => '+592', 'currency' => 'GYD', 'currency_code' => 'GYD', 'currency_symbol' => '', 'flag' => '🇬🇾', 'isActive' => 0],
            ['name' => 'Haiti', 'code' => 'HT', 'iso2' => 'HT', 'iso3' => 'HTI', 'phone_code' => '+509', 'currency' => 'HTG', 'currency_code' => 'HTG', 'currency_symbol' => 'G', 'flag' => '🇭🇹', 'isActive' => 0],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'iso2' => 'VA', 'iso3' => 'VAT', 'phone_code' => '+379', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇻🇦', 'isActive' => 0],
            ['name' => 'Honduras', 'code' => 'HN', 'iso2' => 'HN', 'iso3' => 'HND', 'phone_code' => '+504', 'currency' => 'HNL', 'currency_code' => 'HNL', 'currency_symbol' => 'L', 'flag' => '🇭🇳', 'isActive' => 0],
            ['name' => 'Hong Kong', 'code' => 'HK', 'iso2' => 'HK', 'iso3' => 'HKG', 'phone_code' => '+852', 'currency' => 'HKD', 'currency_code' => 'HKD', 'currency_symbol' => '', 'flag' => '🇭🇰', 'isActive' => 0],
            ['name' => 'Hungary', 'code' => 'HU', 'iso2' => 'HU', 'iso3' => 'HUN', 'phone_code' => '+36', 'currency' => 'HUF', 'currency_code' => 'HUF', 'currency_symbol' => 'Ft', 'flag' => '🇭🇺', 'isActive' => 0],
            ['name' => 'Iceland', 'code' => 'IS', 'iso2' => 'IS', 'iso3' => 'ISL', 'phone_code' => '+354', 'currency' => 'ISK', 'currency_code' => 'ISK', 'currency_symbol' => 'kr', 'flag' => '🇮🇸', 'isActive' => 0],
            ['name' => 'India', 'code' => 'IN', 'iso2' => 'IN', 'iso3' => 'IND', 'phone_code' => '+91', 'currency' => 'INR', 'currency_code' => 'INR', 'currency_symbol' => '₹', 'flag' => '🇮🇳', 'isActive' => 0],
            ['name' => 'Indonesia', 'code' => 'ID', 'iso2' => 'ID', 'iso3' => 'IDN', 'phone_code' => '+62', 'currency' => 'IDR', 'currency_code' => 'IDR', 'currency_symbol' => 'Rp', 'flag' => '🇮🇩', 'isActive' => 0],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR', 'iso2' => 'IR', 'iso3' => 'IRN', 'phone_code' => '+98', 'currency' => 'IRR', 'currency_code' => 'IRR', 'currency_symbol' => '﷼', 'flag' => '🇮🇷', 'isActive' => 0],
            ['name' => 'Iraq', 'code' => 'IQ', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'phone_code' => '+964', 'currency' => 'IQD', 'currency_code' => 'IQD', 'currency_symbol' => 'ع.د', 'flag' => '🇮🇶', 'isActive' => 0],
            ['name' => 'Ireland', 'code' => 'IE', 'iso2' => 'IE', 'iso3' => 'IRL', 'phone_code' => '+353', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇮🇪', 'isActive' => 0],
            ['name' => 'Isle of Man', 'code' => 'IM', 'iso2' => 'IM', 'iso3' => 'IMN', 'phone_code' => '+44-1624', 'currency' => 'GBP', 'currency_code' => 'GBP', 'currency_symbol' => '£', 'flag' => '🇮🇲', 'isActive' => 0],
            ['name' => 'Israel', 'code' => 'IL', 'iso2' => 'IL', 'iso3' => 'ISR', 'phone_code' => '+972', 'currency' => 'ILS', 'currency_code' => 'ILS', 'currency_symbol' => '₪', 'flag' => '🇮🇱', 'isActive' => 0],
            ['name' => 'Italy', 'code' => 'IT', 'iso2' => 'IT', 'iso3' => 'ITA', 'phone_code' => '+39', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇮🇹', 'isActive' => 0],
            ['name' => 'Jamaica', 'code' => 'JM', 'iso2' => 'JM', 'iso3' => 'JAM', 'phone_code' => '+1-876', 'currency' => 'JMD', 'currency_code' => 'JMD', 'currency_symbol' => '', 'flag' => '🇯🇲', 'isActive' => 0],
            ['name' => 'Japan', 'code' => 'JP', 'iso2' => 'JP', 'iso3' => 'JPN', 'phone_code' => '+81', 'currency' => 'JPY', 'currency_code' => 'JPY', 'currency_symbol' => '¥', 'flag' => '🇯🇵', 'isActive' => 0],
            ['name' => 'Jersey', 'code' => 'JE', 'iso2' => 'JE', 'iso3' => 'JEY', 'phone_code' => '+44-1534', 'currency' => 'GBP', 'currency_code' => 'GBP', 'currency_symbol' => '£', 'flag' => '🇯🇪', 'isActive' => 0],
            ['name' => 'Jordan', 'code' => 'JO', 'iso2' => 'JO', 'iso3' => 'JOR', 'phone_code' => '+962', 'currency' => 'JOD', 'currency_code' => 'JOD', 'currency_symbol' => 'د.ا', 'flag' => '🇯🇴', 'isActive' => 0],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'phone_code' => '+7', 'currency' => 'KZT', 'currency_code' => 'KZT', 'currency_symbol' => '₸', 'flag' => '🇰🇿', 'isActive' => 0],
            ['name' => 'Kenya', 'code' => 'KE', 'iso2' => 'KE', 'iso3' => 'KEN', 'phone_code' => '+254', 'currency' => 'KES', 'currency_code' => 'KES', 'currency_symbol' => 'KSh', 'flag' => '🇰🇪', 'isActive' => 0],
            ['name' => 'Kiribati', 'code' => 'KI', 'iso2' => 'KI', 'iso3' => 'KIR', 'phone_code' => '+686', 'currency' => 'AUD', 'currency_code' => 'AUD', 'currency_symbol' => '', 'flag' => '🇰🇮', 'isActive' => 0],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'iso2' => 'KP', 'iso3' => 'PRK', 'phone_code' => '+850', 'currency' => 'KPW', 'currency_code' => 'KPW', 'currency_symbol' => '₩', 'flag' => '🇰🇵', 'isActive' => 0],
            ['name' => 'Korea, Republic of', 'code' => 'KR', 'iso2' => 'KR', 'iso3' => 'KOR', 'phone_code' => '+82', 'currency' => 'KRW', 'currency_code' => 'KRW', 'currency_symbol' => '₩', 'flag' => '🇰🇷', 'isActive' => 0],
            ['name' => 'Kuwait', 'code' => 'KW', 'iso2' => 'KW', 'iso3' => 'KWT', 'phone_code' => '+965', 'currency' => 'KWD', 'currency_code' => 'KWD', 'currency_symbol' => 'د.ك', 'flag' => '🇰🇼', 'isActive' => 0],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'iso2' => 'KG', 'iso3' => 'KGZ', 'phone_code' => '+996', 'currency' => 'KGS', 'currency_code' => 'KGS', 'currency_symbol' => 'сом', 'flag' => '🇰🇬', 'isActive' => 0],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'iso2' => 'LA', 'iso3' => 'LAO', 'phone_code' => '+856', 'currency' => 'LAK', 'currency_code' => 'LAK', 'currency_symbol' => '₭', 'flag' => '🇱🇦', 'isActive' => 0],
            ['name' => 'Latvia', 'code' => 'LV', 'iso2' => 'LV', 'iso3' => 'LVA', 'phone_code' => '+371', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇱🇻', 'isActive' => 0],
            ['name' => 'Lebanon', 'code' => 'LB', 'iso2' => 'LB', 'iso3' => 'LBN', 'phone_code' => '+961', 'currency' => 'LBP', 'currency_code' => 'LBP', 'currency_symbol' => 'ل.ل', 'flag' => '🇱🇧', 'isActive' => 0],
            ['name' => 'Lesotho', 'code' => 'LS', 'iso2' => 'LS', 'iso3' => 'LSO', 'phone_code' => '+266', 'currency' => 'LSL', 'currency_code' => 'LSL', 'currency_symbol' => 'L', 'flag' => '🇱🇸', 'isActive' => 0],
            ['name' => 'Liberia', 'code' => 'LR', 'iso2' => 'LR', 'iso3' => 'LBR', 'phone_code' => '+231', 'currency' => 'LRD', 'currency_code' => 'LRD', 'currency_symbol' => '', 'flag' => '🇱🇷', 'isActive' => 0],
            ['name' => 'Libya', 'code' => 'LY', 'iso2' => 'LY', 'iso3' => 'LBY', 'phone_code' => '+218', 'currency' => 'LYD', 'currency_code' => 'LYD', 'currency_symbol' => 'ل.د', 'flag' => '🇱🇾', 'isActive' => 0],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'iso2' => 'LI', 'iso3' => 'LIE', 'phone_code' => '+423', 'currency' => 'CHF', 'currency_code' => 'CHF', 'currency_symbol' => 'CHF', 'flag' => '🇱🇮', 'isActive' => 0],
            ['name' => 'Lithuania', 'code' => 'LT', 'iso2' => 'LT', 'iso3' => 'LTU', 'phone_code' => '+370', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇱🇹', 'isActive' => 0],
            ['name' => 'Luxembourg', 'code' => 'LU', 'iso2' => 'LU', 'iso3' => 'LUX', 'phone_code' => '+352', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇱🇺', 'isActive' => 0],
            ['name' => 'Macao', 'code' => 'MO', 'iso2' => 'MO', 'iso3' => 'MAC', 'phone_code' => '+853', 'currency' => 'MOP', 'currency_code' => 'MOP', 'currency_symbol' => 'MOP', 'flag' => '🇲🇴', 'isActive' => 0],
            ['name' => 'Madagascar', 'code' => 'MG', 'iso2' => 'MG', 'iso3' => 'MDG', 'phone_code' => '+261', 'currency' => 'MGA', 'currency_code' => 'MGA', 'currency_symbol' => 'Ar', 'flag' => '🇲🇬', 'isActive' => 0],
            ['name' => 'Malawi', 'code' => 'MW', 'iso2' => 'MW', 'iso3' => 'MWI', 'phone_code' => '+265', 'currency' => 'MWK', 'currency_code' => 'MWK', 'currency_symbol' => 'MK', 'flag' => '🇲🇼', 'isActive' => 0],
            ['name' => 'Malaysia', 'code' => 'MY', 'iso2' => 'MY', 'iso3' => 'MYS', 'phone_code' => '+60', 'currency' => 'MYR', 'currency_code' => 'MYR', 'currency_symbol' => 'RM', 'flag' => '🇲🇾', 'isActive' => 0],
            ['name' => 'Maldives', 'code' => 'MV', 'iso2' => 'MV', 'iso3' => 'MDV', 'phone_code' => '+960', 'currency' => 'MVR', 'currency_code' => 'MVR', 'currency_symbol' => 'Rf', 'flag' => '🇲🇻', 'isActive' => 0],
            ['name' => 'Mali', 'code' => 'ML', 'iso2' => 'ML', 'iso3' => 'MLI', 'phone_code' => '+223', 'currency' => 'XOF', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'flag' => '🇲🇱', 'isActive' => 0],
            ['name' => 'Malta', 'code' => 'MT', 'iso2' => 'MT', 'iso3' => 'MLT', 'phone_code' => '+356', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇲🇹', 'isActive' => 0],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'iso2' => 'MH', 'iso3' => 'MHL', 'phone_code' => '+692', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '$', 'flag' => '🇲🇭', 'isActive' => 0],
            ['name' => 'Martinique', 'code' => 'MQ', 'iso2' => 'MQ', 'iso3' => 'MTQ', 'phone_code' => '+596', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇲🇶', 'isActive' => 0],
            ['name' => 'Mauritania', 'code' => 'MR', 'iso2' => 'MR', 'iso3' => 'MRT', 'phone_code' => '+222', 'currency' => 'MRU', 'currency_code' => 'MRU', 'currency_symbol' => 'UM', 'flag' => '🇲🇷', 'isActive' => 0],
            ['name' => 'Mauritius', 'code' => 'MU', 'iso2' => 'MU', 'iso3' => 'MUS', 'phone_code' => '+230', 'currency' => 'MUR', 'currency_code' => 'MUR', 'currency_symbol' => '₨', 'flag' => '🇲🇺', 'isActive' => 0],
            ['name' => 'Mayotte', 'code' => 'YT', 'iso2' => 'YT', 'iso3' => 'MYT', 'phone_code' => '+262', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇾🇹', 'isActive' => 0],
            ['name' => 'Mexico', 'code' => 'MX', 'iso2' => 'MX', 'iso3' => 'MEX', 'phone_code' => '+52', 'currency' => 'MXN', 'currency_code' => 'MXN', 'currency_symbol' => '', 'flag' => '🇲🇽', 'isActive' => 1],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM', 'iso2' => 'FM', 'iso3' => 'FSM', 'phone_code' => '+691', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇫🇲', 'isActive' => 0],
            ['name' => 'Moldova, Republic of', 'code' => 'MD', 'iso2' => 'MD', 'iso3' => 'MDA', 'phone_code' => '+373', 'currency' => 'MDL', 'currency_code' => 'MDL', 'currency_symbol' => 'L', 'flag' => '🇲🇩', 'isActive' => 0],
            ['name' => 'Monaco', 'code' => 'MC', 'iso2' => 'MC', 'iso3' => 'MCO', 'phone_code' => '+377', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇲🇨', 'isActive' => 0],
            ['name' => 'Mongolia', 'code' => 'MN', 'iso2' => 'MN', 'iso3' => 'MNG', 'phone_code' => '+976', 'currency' => 'MNT', 'currency_code' => 'MNT', 'currency_symbol' => '₮', 'flag' => '🇲🇳', 'isActive' => 0],
            ['name' => 'Montenegro', 'code' => 'ME', 'iso2' => 'ME', 'iso3' => 'MNE', 'phone_code' => '+382', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇲🇪', 'isActive' => 0],
            ['name' => 'Montserrat', 'code' => 'MS', 'iso2' => 'MS', 'iso3' => 'MSR', 'phone_code' => '+1-664', 'currency' => 'XCD', 'currency_code' => 'XCD', 'currency_symbol' => '', 'flag' => '🇲🇸', 'isActive' => 0],
            ['name' => 'Morocco', 'code' => 'MA', 'iso2' => 'MA', 'iso3' => 'MAR', 'phone_code' => '+212', 'currency' => 'MAD', 'currency_code' => 'MAD', 'currency_symbol' => 'د.م.', 'flag' => '🇲🇦', 'isActive' => 0],
            ['name' => 'Mozambique', 'code' => 'MZ', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'phone_code' => '+258', 'currency' => 'MZN', 'currency_code' => 'MZN', 'currency_symbol' => 'MT', 'flag' => '🇲🇿', 'isActive' => 0],
            ['name' => 'Myanmar', 'code' => 'MM', 'iso2' => 'MM', 'iso3' => 'MMR', 'phone_code' => '+95', 'currency' => 'MMK', 'currency_code' => 'MMK', 'currency_symbol' => 'K', 'flag' => '🇲🇲', 'isActive' => 0],
            ['name' => 'Namibia', 'code' => 'NA', 'iso2' => 'NA', 'iso3' => 'NAM', 'phone_code' => '+264', 'currency' => 'NAD', 'currency_code' => 'NAD', 'currency_symbol' => '', 'flag' => '🇳🇦', 'isActive' => 0],
            ['name' => 'Nauru', 'code' => 'NR', 'iso2' => 'NR', 'iso3' => 'NRU', 'phone_code' => '+674', 'currency' => 'AUD', 'currency_code' => 'AUD', 'currency_symbol' => '', 'flag' => '🇳🇷', 'isActive' => 0],
            ['name' => 'Nepal', 'code' => 'NP', 'iso2' => 'NP', 'iso3' => 'NPL', 'phone_code' => '+977', 'currency' => 'NPR', 'currency_code' => 'NPR', 'currency_symbol' => '₨', 'flag' => '🇳🇵', 'isActive' => 0],
            ['name' => 'Netherlands', 'code' => 'NL', 'iso2' => 'NL', 'iso3' => 'NLD', 'phone_code' => '+31', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇳🇱', 'isActive' => 0],
            ['name' => 'New Caledonia', 'code' => 'NC', 'iso2' => 'NC', 'iso3' => 'NCL', 'phone_code' => '+687', 'currency' => 'XPF', 'currency_code' => 'XPF', 'currency_symbol' => 'CFPF', 'flag' => '🇳🇨', 'isActive' => 0],
            ['name' => 'New Zealand', 'code' => 'NZ', 'iso2' => 'NZ', 'iso3' => 'NZL', 'phone_code' => '+64', 'currency' => 'NZD', 'currency_code' => 'NZD', 'currency_symbol' => '', 'flag' => '🇳🇿', 'isActive' => 0],
            ['name' => 'Nicaragua', 'code' => 'NI', 'iso2' => 'NI', 'iso3' => 'NIC', 'phone_code' => '+505', 'currency' => 'NIO', 'currency_code' => 'NIO', 'currency_symbol' => 'C$', 'flag' => '🇳🇮', 'isActive' => 0],
            ['name' => 'Niger', 'code' => 'NE', 'iso2' => 'NE', 'iso3' => 'NER', 'phone_code' => '+227', 'currency' => 'XOF', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'flag' => '🇳🇪', 'isActive' => 0],
            ['name' => 'Nigeria', 'code' => 'NG', 'iso2' => 'NG', 'iso3' => 'NGA', 'phone_code' => '+234', 'currency' => 'NGN', 'currency_code' => 'NGN', 'currency_symbol' => '₦', 'flag' => '🇳🇬', 'isActive' => 0],
            ['name' => 'Niue', 'code' => 'NU', 'iso2' => 'NU', 'iso3' => 'NIU', 'phone_code' => '+683', 'currency' => 'NZD', 'currency_code' => 'NZD', 'currency_symbol' => '', 'flag' => '🇳🇺', 'isActive' => 0],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'iso2' => 'NF', 'iso3' => 'NFK', 'phone_code' => '+672', 'currency' => 'AUD', 'currency_code' => 'AUD', 'currency_symbol' => '', 'flag' => '🇳🇫', 'isActive' => 0],
            ['name' => 'North Macedonia', 'code' => 'MK', 'iso2' => 'MK', 'iso3' => 'MKD', 'phone_code' => '+389', 'currency' => 'MKD', 'currency_code' => 'MKD', 'currency_symbol' => 'ден', 'flag' => '🇲🇰', 'isActive' => 0],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'iso2' => 'MP', 'iso3' => 'MNP', 'phone_code' => '+1-670', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇲🇵', 'isActive' => 0],
            ['name' => 'Norway', 'code' => 'NO', 'iso2' => 'NO', 'iso3' => 'NOR', 'phone_code' => '+47', 'currency' => 'NOK', 'currency_code' => 'NOK', 'currency_symbol' => 'kr', 'flag' => '🇳🇴', 'isActive' => 0],
            ['name' => 'Oman', 'code' => 'OM', 'iso2' => 'OM', 'iso3' => 'OMN', 'phone_code' => '+968', 'currency' => 'OMR', 'currency_code' => 'OMR', 'currency_symbol' => 'ر.ع.', 'flag' => '🇴🇲', 'isActive' => 0],
            ['name' => 'Pakistan', 'code' => 'PK', 'iso2' => 'PK', 'iso3' => 'PAK', 'phone_code' => '+92', 'currency' => 'PKR', 'currency_code' => 'PKR', 'currency_symbol' => '₨', 'flag' => '🇵🇰', 'isActive' => 0],
            ['name' => 'Palau', 'code' => 'PW', 'iso2' => 'PW', 'iso3' => 'PLW', 'phone_code' => '+680', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇵🇼', 'isActive' => 0],
            ['name' => 'Palestine, State of', 'code' => 'PS', 'iso2' => 'PS', 'iso3' => 'PSE', 'phone_code' => '+970', 'currency' => 'ILS', 'currency_code' => 'ILS', 'currency_symbol' => '₪', 'flag' => '🇵🇸', 'isActive' => 0],
            ['name' => 'Panama', 'code' => 'PA', 'iso2' => 'PA', 'iso3' => 'PAN', 'phone_code' => '+507', 'currency' => 'PAB', 'currency_code' => 'PAB', 'currency_symbol' => 'PAB', 'flag' => '🇵🇦', 'isActive' => 0],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'iso2' => 'PG', 'iso3' => 'PNG', 'phone_code' => '+675', 'currency' => 'PGK', 'currency_code' => 'PGK', 'currency_symbol' => 'K', 'flag' => '🇵🇬', 'isActive' => 0],
            ['name' => 'Paraguay', 'code' => 'PY', 'iso2' => 'PY', 'iso3' => 'PRY', 'phone_code' => '+595', 'currency' => 'PYG', 'currency_code' => 'PYG', 'currency_symbol' => '₲', 'flag' => '🇵🇾', 'isActive' => 0],
            ['name' => 'Peru', 'code' => 'PE', 'iso2' => 'PE', 'iso3' => 'PER', 'phone_code' => '+51', 'currency' => 'PEN', 'currency_code' => 'PEN', 'currency_symbol' => 'S/.', 'flag' => '🇵🇪', 'isActive' => 0],
            ['name' => 'Philippines', 'code' => 'PH', 'iso2' => 'PH', 'iso3' => 'PHL', 'phone_code' => '+63', 'currency' => 'PHP', 'currency_code' => 'PHP', 'currency_symbol' => '₱', 'flag' => '🇵🇭', 'isActive' => 0],
            ['name' => 'Poland', 'code' => 'PL', 'iso2' => 'PL', 'iso3' => 'POL', 'phone_code' => '+48', 'currency' => 'PLN', 'currency_code' => 'PLN', 'currency_symbol' => 'zł', 'flag' => '🇵🇱', 'isActive' => 0],
            ['name' => 'Portugal', 'code' => 'PT', 'iso2' => 'PT', 'iso3' => 'PRT', 'phone_code' => '+351', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇵🇹', 'isActive' => 0],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'iso2' => 'PR', 'iso3' => 'PRI', 'phone_code' => '+1-787, 1-939', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇵🇷', 'isActive' => 0],
            ['name' => 'Qatar', 'code' => 'QA', 'iso2' => 'QA', 'iso3' => 'QAT', 'phone_code' => '+974', 'currency' => 'QAR', 'currency_code' => 'QAR', 'currency_symbol' => 'ر.ق', 'flag' => '🇶🇦', 'isActive' => 0],
            ['name' => 'Romania', 'code' => 'RO', 'iso2' => 'RO', 'iso3' => 'ROU', 'phone_code' => '+40', 'currency' => 'RON', 'currency_code' => 'RON', 'currency_symbol' => 'lei', 'flag' => '🇷🇴', 'isActive' => 0],
            ['name' => 'Russian Federation', 'code' => 'RU', 'iso2' => 'RU', 'iso3' => 'RUS', 'phone_code' => '+7', 'currency' => 'RUB', 'currency_code' => 'RUB', 'currency_symbol' => '₽', 'flag' => '🇷🇺', 'isActive' => 0],
            ['name' => 'Rwanda', 'code' => 'RW', 'iso2' => 'RW', 'iso3' => 'RWA', 'phone_code' => '+250', 'currency' => 'RWF', 'currency_code' => 'RWF', 'currency_symbol' => 'FRw', 'flag' => '🇷🇼', 'isActive' => 0],
            ['name' => 'Saint Barthélemy', 'code' => 'BL', 'iso2' => 'BL', 'iso3' => 'BLM', 'phone_code' => '+590', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇧🇱', 'isActive' => 0],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH', 'iso2' => 'SH', 'iso3' => 'SHN', 'phone_code' => '+290', 'currency' => 'SHP', 'currency_code' => 'SHP', 'currency_symbol' => '£', 'flag' => '🇸🇭', 'isActive' => 0],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'iso2' => 'KN', 'iso3' => 'KNA', 'phone_code' => '+1-869', 'currency' => 'XCD', 'currency_code' => 'XCD', 'currency_symbol' => '', 'flag' => '🇰🇳', 'isActive' => 0],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'iso2' => 'LC', 'iso3' => 'LCA', 'phone_code' => '+1-758', 'currency' => 'XCD', 'currency_code' => 'XCD', 'currency_symbol' => '$', 'flag' => '🇱🇨', 'isActive' => 0],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF', 'iso2' => 'MF', 'iso3' => 'MAF', 'phone_code' => '+590', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇲🇫', 'isActive' => 0],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'iso2' => 'PM', 'iso3' => 'SPM', 'phone_code' => '+508', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇵🇲', 'isActive' => 0],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'iso2' => 'VC', 'iso3' => 'VCT', 'phone_code' => '+1-784', 'currency' => 'XCD', 'currency_code' => 'XCD', 'currency_symbol' => '', 'flag' => '🇻🇨', 'isActive' => 0],
            ['name' => 'Samoa', 'code' => 'WS', 'iso2' => 'WS', 'iso3' => 'WSM', 'phone_code' => '+685', 'currency' => 'WST', 'currency_code' => 'WST', 'currency_symbol' => 'T', 'flag' => '🇼🇸', 'isActive' => 0],
            ['name' => 'San Marino', 'code' => 'SM', 'iso2' => 'SM', 'iso3' => 'SMR', 'phone_code' => '+378', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇸🇲', 'isActive' => 0],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'iso2' => 'ST', 'iso3' => 'STP', 'phone_code' => '+239', 'currency' => 'STD', 'currency_code' => 'STD', 'currency_symbol' => 'Db', 'flag' => '🇸🇹', 'isActive' => 0],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'iso2' => 'SA', 'iso3' => 'SAU', 'phone_code' => '+966', 'currency' => 'SAR', 'currency_code' => 'SAR', 'currency_symbol' => 'ر.س', 'flag' => '🇸🇦', 'isActive' => 0],
            ['name' => 'Senegal', 'code' => 'SN', 'iso2' => 'SN', 'iso3' => 'SEN', 'phone_code' => '+221', 'currency' => 'XOF', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'flag' => '🇸🇳', 'isActive' => 0],
            ['name' => 'Serbia', 'code' => 'RS', 'iso2' => 'RS', 'iso3' => 'SRB', 'phone_code' => '+381', 'currency' => 'RSD', 'currency_code' => 'RSD', 'currency_symbol' => 'дин.', 'flag' => '🇷🇸', 'isActive' => 0],
            ['name' => 'Seychelles', 'code' => 'SC', 'iso2' => 'SC', 'iso3' => 'SYC', 'phone_code' => '+248', 'currency' => 'SCR', 'currency_code' => 'SCR', 'currency_symbol' => '₨', 'flag' => '🇸🇨', 'isActive' => 0],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'iso2' => 'SL', 'iso3' => 'SLE', 'phone_code' => '+232', 'currency' => 'SLL', 'currency_code' => 'SLL', 'currency_symbol' => 'Le', 'flag' => '🇸🇱', 'isActive' => 0],
            ['name' => 'Singapore', 'code' => 'SG', 'iso2' => 'SG', 'iso3' => 'SGP', 'phone_code' => '+65', 'currency' => 'SGD', 'currency_code' => 'SGD', 'currency_symbol' => '', 'flag' => '🇸🇬', 'isActive' => 0],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX', 'iso2' => 'SX', 'iso3' => 'SXM', 'phone_code' => '+1-721', 'currency' => 'ANG', 'currency_code' => 'ANG', 'currency_symbol' => 'ƒ', 'flag' => '🇸🇽', 'isActive' => 0],
            ['name' => 'Slovakia', 'code' => 'SK', 'iso2' => 'SK', 'iso3' => 'SVK', 'phone_code' => '+421', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇸🇰', 'isActive' => 0],
            ['name' => 'Slovenia', 'code' => 'SI', 'iso2' => 'SI', 'iso3' => 'SVN', 'phone_code' => '+386', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇸🇮', 'isActive' => 0],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'iso2' => 'SB', 'iso3' => 'SLB', 'phone_code' => '+677', 'currency' => 'SBD', 'currency_code' => 'SBD', 'currency_symbol' => '', 'flag' => '🇸🇧', 'isActive' => 0],
            ['name' => 'Somalia', 'code' => 'SO', 'iso2' => 'SO', 'iso3' => 'SOM', 'phone_code' => '+252', 'currency' => 'SOS', 'currency_code' => 'SOS', 'currency_symbol' => 'Sh.So.', 'flag' => '🇸🇴', 'isActive' => 0],
            ['name' => 'South Africa', 'code' => 'ZA', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'phone_code' => '+27', 'currency' => 'ZAR', 'currency_code' => 'ZAR', 'currency_symbol' => 'R', 'flag' => '🇿🇦', 'isActive' => 0],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'iso2' => 'GS', 'iso3' => 'SGS', 'phone_code' => '+', 'currency' => 'GBP', 'currency_code' => 'GBP', 'currency_symbol' => '£', 'flag' => '🇬🇸', 'isActive' => 0],
            ['name' => 'South Sudan', 'code' => 'SS', 'iso2' => 'SS', 'iso3' => 'SSD', 'phone_code' => '+211', 'currency' => 'SSP', 'currency_code' => 'SSP', 'currency_symbol' => '£', 'flag' => '🇸🇸', 'isActive' => 0],
            ['name' => 'Spain', 'code' => 'ES', 'iso2' => 'ES', 'iso3' => 'ESP', 'phone_code' => '+34', 'currency' => 'EUR', 'currency_code' => 'EUR', 'currency_symbol' => '€', 'flag' => '🇪🇸', 'isActive' => 0],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'iso2' => 'LK', 'iso3' => 'LKA', 'phone_code' => '+94', 'currency' => 'LKR', 'currency_code' => 'LKR', 'currency_symbol' => 'රු', 'flag' => '🇱🇰', 'isActive' => 0],
            ['name' => 'Sudan', 'code' => 'SD', 'iso2' => 'SD', 'iso3' => 'SDN', 'phone_code' => '+249', 'currency' => 'SDG', 'currency_code' => 'SDG', 'currency_symbol' => 'ج.س.', 'flag' => '🇸🇩', 'isActive' => 0],
            ['name' => 'Suriname', 'code' => 'SR', 'iso2' => 'SR', 'iso3' => 'SUR', 'phone_code' => '+597', 'currency' => 'SRD', 'currency_code' => 'SRD', 'currency_symbol' => '', 'flag' => '🇸🇷', 'isActive' => 0],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'iso2' => 'SJ', 'iso3' => 'SJM', 'phone_code' => '+47', 'currency' => 'NOK', 'currency_code' => 'NOK', 'currency_symbol' => 'kr', 'flag' => '🇸🇯', 'isActive' => 0],
            ['name' => 'Sweden', 'code' => 'SE', 'iso2' => 'SE', 'iso3' => 'SWE', 'phone_code' => '+46', 'currency' => 'SEK', 'currency_code' => 'SEK', 'currency_symbol' => 'kr', 'flag' => '🇸🇪', 'isActive' => 0],
            ['name' => 'Switzerland', 'code' => 'CH', 'iso2' => 'CH', 'iso3' => 'CHE', 'phone_code' => '+41', 'currency' => 'CHF', 'currency_code' => 'CHF', 'currency_symbol' => 'CHF', 'flag' => '🇨🇭', 'isActive' => 0],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'iso2' => 'SY', 'iso3' => 'SYR', 'phone_code' => '+963', 'currency' => 'SYP', 'currency_code' => 'SYP', 'currency_symbol' => 'ل.س', 'flag' => '🇸🇾', 'isActive' => 0],
            ['name' => 'Taiwan, Province of China', 'code' => 'TW', 'iso2' => 'TW', 'iso3' => 'TWN', 'phone_code' => '+886', 'currency' => 'TWD', 'currency_code' => 'TWD', 'currency_symbol' => '', 'flag' => '🇹🇼', 'isActive' => 0],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'iso2' => 'TJ', 'iso3' => 'TJK', 'phone_code' => '+992', 'currency' => 'TJS', 'currency_code' => 'TJS', 'currency_symbol' => 'ЅМ', 'flag' => '🇹🇯', 'isActive' => 0],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'iso2' => 'TZ', 'iso3' => 'TZA', 'phone_code' => '+255', 'currency' => 'TZS', 'currency_code' => 'TZS', 'currency_symbol' => 'TSh', 'flag' => '🇹🇿', 'isActive' => 0],
            ['name' => 'Thailand', 'code' => 'TH', 'iso2' => 'TH', 'iso3' => 'THA', 'phone_code' => '+66', 'currency' => 'THB', 'currency_code' => 'THB', 'currency_symbol' => '฿', 'flag' => '🇹🇭', 'isActive' => 0],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'iso2' => 'TL', 'iso3' => 'TLS', 'phone_code' => '+670', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇹🇱', 'isActive' => 0],
            ['name' => 'Togo', 'code' => 'TG', 'iso2' => 'TG', 'iso3' => 'TGO', 'phone_code' => '+228', 'currency' => 'XOF', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA', 'flag' => '🇹🇬', 'isActive' => 0],
            ['name' => 'Tokelau', 'code' => 'TK', 'iso2' => 'TK', 'iso3' => 'TKL', 'phone_code' => '+690', 'currency' => 'NZD', 'currency_code' => 'NZD', 'currency_symbol' => '', 'flag' => '🇹🇰', 'isActive' => 0],
            ['name' => 'Tonga', 'code' => 'TO', 'iso2' => 'TO', 'iso3' => 'TON', 'phone_code' => '+676', 'currency' => 'TOP', 'currency_code' => 'TOP', 'currency_symbol' => 'T', 'flag' => '🇹🇴', 'isActive' => 0],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'iso2' => 'TT', 'iso3' => 'TTO', 'phone_code' => '+1-868', 'currency' => 'TTD', 'currency_code' => 'TTD', 'currency_symbol' => '', 'flag' => '🇹🇹', 'isActive' => 0],
            ['name' => 'Tunisia', 'code' => 'TN', 'iso2' => 'TN', 'iso3' => 'TUN', 'phone_code' => '+216', 'currency' => 'TND', 'currency_code' => 'TND', 'currency_symbol' => 'د.ت', 'flag' => '🇹🇳', 'isActive' => 0],
            ['name' => 'Turkey', 'code' => 'TR', 'iso2' => 'TR', 'iso3' => 'TUR', 'phone_code' => '+90', 'currency' => 'TRY', 'currency_code' => 'TRY', 'currency_symbol' => '₺', 'flag' => '🇹🇷', 'isActive' => 0],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'iso2' => 'TM', 'iso3' => 'TKM', 'phone_code' => '+993', 'currency' => 'TMT', 'currency_code' => 'TMT', 'currency_symbol' => 'T', 'flag' => '🇹🇲', 'isActive' => 0],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'iso2' => 'TC', 'iso3' => 'TCA', 'phone_code' => '+1-649', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇹🇨', 'isActive' => 0],
            ['name' => 'Tuvalu', 'code' => 'TV', 'iso2' => 'TV', 'iso3' => 'TUV', 'phone_code' => '+688', 'currency' => 'AUD', 'currency_code' => 'AUD', 'currency_symbol' => '', 'flag' => '🇹🇻', 'isActive' => 0],
            ['name' => 'Uganda', 'code' => 'UG', 'iso2' => 'UG', 'iso3' => 'UGA', 'phone_code' => '+256', 'currency' => 'UGX', 'currency_code' => 'UGX', 'currency_symbol' => 'USh', 'flag' => '🇺🇬', 'isActive' => 0],
            ['name' => 'Ukraine', 'code' => 'UA', 'iso2' => 'UA', 'iso3' => 'UKR', 'phone_code' => '+380', 'currency' => 'UAH', 'currency_code' => 'UAH', 'currency_symbol' => '₴', 'flag' => '🇺🇦', 'isActive' => 0],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'iso2' => 'AE', 'iso3' => 'ARE', 'phone_code' => '+971', 'currency' => 'AED', 'currency_code' => 'AED', 'currency_symbol' => 'د.إ', 'flag' => '🇦🇪', 'isActive' => 0],
            ['name' => 'United Kingdom', 'code' => 'GB', 'iso2' => 'GB', 'iso3' => 'GBR', 'phone_code' => '+44', 'currency' => 'GBP', 'currency_code' => 'GBP', 'currency_symbol' => '£', 'flag' => '🇬🇧', 'isActive' => 0],
            ['name' => 'United States', 'code' => 'US', 'iso2' => 'US', 'iso3' => 'USA', 'phone_code' => '+1', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇺🇸', 'isActive' => 1],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'iso2' => 'UM', 'iso3' => 'UMI', 'phone_code' => '+1', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '', 'flag' => '🇺🇲', 'isActive' => 0],
            ['name' => 'Uruguay', 'code' => 'UY', 'iso2' => 'UY', 'iso3' => 'URY', 'phone_code' => '+598', 'currency' => 'UYU', 'currency_code' => 'UYU', 'currency_symbol' => '', 'flag' => '🇺🇾', 'isActive' => 0],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'iso2' => 'UZ', 'iso3' => 'UZB', 'phone_code' => '+998', 'currency' => 'UZS', 'currency_code' => 'UZS', 'currency_symbol' => 'лв', 'flag' => '🇺🇿', 'isActive' => 0],
            ['name' => 'Vanuatu', 'code' => 'VU', 'iso2' => 'VU', 'iso3' => 'VUT', 'phone_code' => '+678', 'currency' => 'VUV', 'currency_code' => 'VUV', 'currency_symbol' => 'Vt', 'flag' => '🇻🇺', 'isActive' => 0],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE', 'iso2' => 'VE', 'iso3' => 'VEN', 'phone_code' => '+58', 'currency' => 'VES', 'currency_code' => 'VES', 'currency_symbol' => 'Bs.S', 'flag' => '🇻🇪', 'isActive' => 0],
            ['name' => 'Viet Nam', 'code' => 'VN', 'iso2' => 'VN', 'iso3' => 'VNM', 'phone_code' => '+84', 'currency' => 'VND', 'currency_code' => 'VND', 'currency_symbol' => '₫', 'flag' => '🇻🇳', 'isActive' => 0],
            ['name' => 'Virgin Islands, British', 'code' => 'VG', 'iso2' => 'VG', 'iso3' => 'VGB', 'phone_code' => '+1-284', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '$', 'flag' => '🇻🇬', 'isActive' => 0],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'iso2' => 'VI', 'iso3' => 'VIR', 'phone_code' => '+1-340', 'currency' => 'USD', 'currency_code' => 'USD', 'currency_symbol' => '$', 'flag' => '🇻🇮', 'isActive' => 0],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'iso2' => 'WF', 'iso3' => 'WLF', 'phone_code' => '+681', 'currency' => 'XPF', 'currency_code' => 'XPF', 'currency_symbol' => 'CFPF', 'flag' => '🇼🇫', 'isActive' => 0],
            ['name' => 'Yemen', 'code' => 'YE', 'iso2' => 'YE', 'iso3' => 'YEM', 'phone_code' => '+967', 'currency' => 'YER', 'currency_code' => 'YER', 'currency_symbol' => '﷼', 'flag' => '🇾🇪', 'isActive' => 0],
            ['name' => 'Zambia', 'code' => 'ZM', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'phone_code' => '+260', 'currency' => 'ZMW', 'currency_code' => 'ZMW', 'currency_symbol' => 'ZK', 'flag' => '🇿🇲', 'isActive' => 0],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'phone_code' => '+263', 'currency' => 'ZWL', 'currency_code' => 'ZWL', 'currency_symbol' => '$', 'flag' => '🇿🇼', 'isActive' => 0]
            ];
        foreach ($countries as $country) {
            DB::table('countries')->insert($country);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
